# Generated by Django 3.2.3 on 2021-05-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210524_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='covid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
