# Generated by Django 3.2.4 on 2021-06-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='checksum',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
